### ISSUE TITLE
CUDA  out of memory

### ISSUE THREAD

**Issue by Z-mingyu** [JihuaPeng/KTPFormer#12]
hello , I excuted `python run_ktpformer.py -k cpn_ft_h36m_dbb -f 243 -s 128 -l log/run -c checkpoint
`  in a RTX 3090 card , and  enntered the following errors

> Loading 2D detections...
> INFO: Receptive field: 243 frames
> INFO: Trainable parameter count: 35.21343 Million
> INFO: Testing on 543344 frames
> INFO: Training on 1559752 frames
> ** Note: reported losses are averaged over all frames.
> ** The final evaluation will be carried out after the last training epoch.
> Traceback (most recent call last):
>   File "run_ktpformer.py", line 401, in <module>
>     predicted_3d_pos = model_pos_train(inputs_2d)
>   File "/home/zmy/anaconda3/envs/pytorch1131/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/zmy/anaconda3/envs/pytorch1131/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/zmy/anaconda3/envs/pytorch1131/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/zmy/KTPFormer/common/model_ktpformer.py", line 647, in forward
>     x = self.ST_foward(x)
>   File "/home/zmy/KTPFormer/common/model_ktpformer.py", line 609, in ST_foward
>     x = steblock(x)
>   File "/home/zmy/anaconda3/envs/pytorch1131/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/zmy/KTPFormer/common/model_ktpformer.py", line 489, in forward
>     x = x + self.drop_path(self.attn(self.norm1(x), vis=vis))
>   File "/home/zmy/anaconda3/envs/pytorch1131/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/zmy/KTPFormer/common/model_ktpformer.py", line 190, in forward
>     qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
>   File "/home/zmy/anaconda3/envs/pytorch1131/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/zmy/anaconda3/envs/pytorch1131/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
>     return F.linear(input, self.weight, self.bias)
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 194.00 MiB (GPU 0; 23.68 GiB total capacity; 22.39 GiB already allocated; 82.25 MiB free; 22.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I didn't modify any code and found that you train the model in a single RTX 3090. So, why did the error occur?
I'm looking forward to your reply

**Comment by 15333287671** [comment]
I encountered a similar issue before. I fixed it by changing the '+=' in the KPAattention module to '=+'

**Comment by JihuaPeng** [comment]
If you encounter insufficient GPU memory, you can increase the ”--stride“ parameter.
